@startuml Secuencia Cierre de vuelo

participant Vuelo
participant Notification.Supervisor
participant Notification
participant Reservas.Registry
participant Reserva
participant Entidades.Usuario.Registry

Vuelo -> Notification.Supervisor: Notificar cierre de vuelo
note left: Ya sea por el send_after \no el cierre computado se \nprocede con lo siguiente.
Notification.Supervisor -> Notification: Notificar cierre
Notification -> Reservas.Registry: buscar las reservas\nde un vuelo
Reservas.Registry -> Notification: devolver reservas
Notification -> Reserva: cerrar reservas
Reserva -> Entidades.Usuario.Registry: buscar usuario
Entidades.Usuario.Registry -> Reserva: devolver usuario
Reserva -> Entidades.Usuario: cerrar reserva\nde usuario

@enduml