@startuml Secuencia Creacion de alertas

actor Usuario
participant Interface.Usuarios
participant Alertas.DynamicSupervisor
participant Alertas.Registry
participant Alerta

== Alerta por mes == 

Usuario -> Interface.Usuarios: crear alerta
Interface.Usuarios -> Alertas.DynamicSupervisor: crear alerta por mes
Alertas.DynamicSupervisor -> Alertas.Registry: crear la alerta
Alertas.Registry -> Alertas.DynamicSupervisor: {:ok, pid}
Alertas.DynamicSupervisor -> Alerta: suscribir al usuario a la alerta de mes
Alerta -> Alertas.DynamicSupervisor: :ok
Alertas.DynamicSupervisor -> Interface.Usuarios: alerta creada
Interface.Usuarios -> Usuario: alerta creada

== Alerta por fecha == 

Usuario -> Interface.Usuarios: crear alerta
Interface.Usuarios -> Alertas.DynamicSupervisor: crear alerta por fecha
Alertas.DynamicSupervisor -> Alertas.Registry: crear la alerta
Alertas.Registry -> Alertas.DynamicSupervisor: {:ok, pid}
Alertas.DynamicSupervisor -> Alerta: suscribir al usuario a la alerta de fecha
Alerta -> Alertas.DynamicSupervisor: :ok
Alertas.DynamicSupervisor -> Interface.Usuarios: alerta creada
Interface.Usuarios -> Usuario: alerta creada


== Alerta por destino == 

Usuario -> Interface.Usuarios: crear alerta
Interface.Usuarios -> Alertas.DynamicSupervisor: crear alerta por destino
Alertas.DynamicSupervisor -> Alertas.Registry: crear la alerta
Alertas.Registry -> Alertas.DynamicSupervisor: {:ok, pid}
Alertas.DynamicSupervisor -> Alerta: suscribir al usuario a la alerta de destino
Alerta -> Alertas.DynamicSupervisor: :ok
Alertas.DynamicSupervisor -> Interface.Usuarios: alerta creada
Interface.Usuarios -> Usuario: alerta creada

== Alerta por origen == 

Usuario -> Interface.Usuarios: crear alerta
Interface.Usuarios -> Alertas.DynamicSupervisor: crear alerta por origen
Alertas.DynamicSupervisor -> Alertas.Registry: crear la alerta
Alertas.Registry -> Alertas.DynamicSupervisor: {:ok, pid}
Alertas.DynamicSupervisor -> Alerta: suscribir al usuario a la alerta de origen
Alerta -> Alertas.DynamicSupervisor: :ok
Alertas.DynamicSupervisor -> Interface.Usuarios: alerta creada
Interface.Usuarios -> Usuario: alerta creada

@enduml