@startuml Secuencia Publicar Vuelo 
actor Aerolinea
participant Aerolina.Interface.Worker
participant Vuelos.Worker
database Vuelos.DB
database Alertas.DB
participant Alertas.Notifier
participant Usuario.Interface.Worker
actor Usuario


Aerolinea -> "Aerolina.Interface.Worker": Publicar vuelo
"Aerolina.Interface.Worker" -> Vuelos.Worker: Publicar vuelo
Vuelos.Worker -> Vuelos.DB: Agregar vuelo
Vuelos.Worker -> "Aerolina.Interface.Worker": Vuelo agregado
"Aerolina.Interface.Worker" -> Aerolinea: OK
Vuelos.DB --> Alertas.Notifier: Notificar nuevo vuelo
Alertas.Notifier -> Alertas.DB: Fetch de alertas
Alertas.DB -> Alertas.Notifier: Devuelve alertas
activate Alertas.Notifier
note right: Evalua condiciones de alertas

Alertas.Notifier -> Usuario.Interface.Worker: Notificar usuario de nuevo vuelo
deactivate Alertas.Notifier
Usuario.Interface.Worker -> Usuario: Nuevo vuelo publicado

@enduml
